### ISSUE TITLE
RDEPENDS on bash ?

### ISSUE THREAD

**Issue by insatomcat** [dimtass/meta-elastic-beats#3]
Hello,

Since the wrapper exec-script depends on bash, shouldn't the recipe contains a standard RDEPENDS on bash ?
Right now it's only for the -dev package:
[
https://github.com/dimtass/meta-elastic-beats/blob/00c2b8c814ef259ca6199b5a7753ea0e104aa332/recipes-devops/elastic-beats/elastic-beats.inc#L29](
https://github.com/dimtass/meta-elastic-beats/blob/00c2b8c814ef259ca6199b5a7753ea0e104aa332/recipes-devops/elastic-beats/elastic-beats.inc#L29)

Thanks.

**Comment by dimtass** [comment]
It was some time ago that I've done this. Yocto sometimes is a mess and things change a lot between versions. Maybe this was needed only for -dev at that point and not anymore. I don't remember tbh.

Do you have issues when removing it or any other issue?

**Comment by insatomcat** [comment]
Indeed I had to add bash as standard rdepends to make in work (using dunfell, and beat was probably the first package in my distribution to need bash).
PR #6
